#!/usr/bin/env bash

WD=`pwd`; SCRIPT=`realpath $0`; cd `dirname $SCRIPT`
source ~/.rvm/scripts/rvm; rvm use 2.5.3

dbname=$1
dumpfile=${2:-$1}

dropdb $dbname || exit 1
createdb -O root $dbname
cd ~/miqdb
psql -U root $dbname < $dumpfile
cd ~/git/manageiq
bundle exec tools/fix_auth.rb --invalid bogus $dbname
./bin/rails db:migrate

cd $WD