#!/usr/bin/env bash
# Available options: --with-v2v-plugin

SCRIPT=`realpath $0`; cd `dirname $SCRIPT`

echo "Switching to ruby-2.4.2"
source ~/.rvm/scripts/rvm
rvm use 2.4.2

echo "Checking/installing homebrew dependencies..."
brew install git pkg-config memcached postgresql cmake node yarn

echo "Unlinking homebrew's xz if present to prevent conflicts with system xz libraries..."
brew unlink xz

echo "Checking/installing bundler..."
gem install bundler

echo "Checking/installing foreman..."
gem install foreman

echo "Checking/installing npm dependencies..."
sudo npm install -g bower yarn gulp-cli webpack

echo "Enabling PostgreSQL on boot..."
mkdir -p ~/Library/LaunchAgents
ln -sfv /usr/local/opt/postgresql/*.plist ~/Library/LaunchAgents
launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist

echo "Creating the ManageIQ superuser..."
psql -d postgres -c "CREATE ROLE root SUPERUSER LOGIN PASSWORD 'smartvm'"

echo "Enabling Memcached on boot..."
ln -sfv /usr/local/opt/memcached/homebrew.mxcl.memcached.plist ~/Library/LaunchAgents
launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.memcached.plist

echo "Cloning the manageiq and manageiq-ui-classic repositories..."
cd ..
git clone https://github.com/ManageIQ/manageiq.git
mkdir -p manageiq/plugins
cd manageiq/plugins
git clone https://github.com/ManageIQ/manageiq-ui-classic

if [ "$1" = "--with-v2v-plugin" ] ; then
  echo "[v2v only] Switching to priley's v2v branch of manageiq-ui-classic..."
  cd manageiq-ui-classic
  git remote add priley https://github.com/priley86/manageiq-ui-classic.git
  git fetch priley v2v:v2v
  git checkout v2v
  cd ..

  echo "[v2v only] Cloning the miq_v2v_ui_plugin repository..."
  git clone https://github.com/priley86/miq_v2v_ui_plugin

  echo "[v2v only] Setting up miq_v2v_ui_plugin..."
  cd miq_v2v_ui_plugin
  npm install
  cd ..
fi

cd ../../

echo "Creating/replacing manageiq/Gemfile..."
cp -v miq_mac_dev/Gemfile.example manageiq/Gemfile
echo "Creating/replacing manageiq/Procfile..."
cp -v miq_mac_dev/Procfile.example manageiq/Procfile
echo "Creating/replacing manageiq/bundler.d/Gemfile.dev.rb..."
mkdir -p manageiq/bundler.d
cp -v miq_mac_dev/Gemfile.dev.rb.example manageiq/bundler.d/Gemfile.dev.rb

echo "Setting up manageiq..."
cd manageiq
bin/setup
bin/update
cd ..

echo "Creating a symbolic link to local manageiq in manageiq-ui-classic/spec/manageiq..."
ln -sv ../../../ manageiq/plugins/manageiq-ui-classic/spec/manageiq

echo "Setting up manageiq-ui-classic..."
cd manageiq/plugins/manageiq-ui-classic
npm install
bin/setup
bin/update
bundle exec rake update:ui

echo "DONE!"
echo
echo "To start the manageiq rails server directly (foreground option 1):"
echo "  miq_mac_dev/rails"
echo "or:"
echo "  cd manageiq"
echo "  bundle exec rails s"
echo
echo "To start manageiq with foreman (foreground option 2):"
echo "  miq_mac_dev/foreman"
echo "or:"
echo "  cd manageiq"
echo "  foreman start -p 3000"
echo
echo "To start manageiq with evm (background option):"
echo "  miq_mac_dev/evm"
echo "or:"
echo "  cd manageiq"
echo "  bundle exec rake evm:start"
echo
echo "Then navigate a browser to http://localhost:3000/ and log in with admin/smartvm."
echo
echo "For hot reloading, you'll need webpack. To start manageiq-ui-classic with webpack:"
echo "  miq_mac_dev/webpack"
echo "or:"
echo "  cd manageiq/plugins/manageiq-ui-classic"
echo "  NODE_ENV=development ./node_modules/.bin/webpack-dev-server --config config/webpack/development.js"
echo