#!/bin/sh

SCRIPT=`realpath $0`; cd `dirname $SCRIPT`

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
rvm use 2.4.2

cd ../manageiq/plugins/manageiq-ui-classic
npm install
bundle exec rake update:ui