#!/usr/bin/env bash

WD=`pwd`; SCRIPT=`realpath $0`; cd `dirname $SCRIPT`
source ~/.rvm/scripts/rvm; rvm use 2.5.3

cd ../manageiq/plugins/manageiq-ui-classic
npm install
bundle install
bundle exec rake update:ui

cd $WD