#!/bin/sh

if [ -d "../miq_mac_dev" -o -d "${PWD}/miq_mac_dev" ]
then
  echo "Preparing..."
  cd ../miq_mac_dev 2>/dev/null || cd miq_mac_dev
else
  echo "Run this script from the miq_mac_dev directory or its parent."
  exit 1
fi

cd manageiq-ui-classic
env NODE_ENV=development ./node_modules/.bin/webpack-dev-server --config config/webpack/development.js