#!/usr/bin/env bash

WD=`pwd`; SCRIPT=`realpath $0`; cd `dirname $SCRIPT`

cd ../manageiq/plugins/manageiq-ui-classic
env NODE_ENV=development WEBPACK_EXCLUDE_NODE_MODULES=1 ./node_modules/.bin/webpack-dev-server --config config/webpack/development.js

cd $WD